package APCompSci.Assignments.Assign9;

/**
 * ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 * S-h-e-n-e-n-d-e-h-o-w-a--H-i-g-h--S-c-h-o-o-l--T-e-c-h-n-o-l-o-g-y--D-e-p-t
 * ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 *      FILE:       AboutFrame.java
 *      DATE:       2011
 *      AUTHOR:     mr Hanley
 *      VERSION:    2.0
 *      PURPOSE:    Pop Up Easter Egg with Secret Message
 *
 * ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 *
 * m-r-h-a-n-l-e-y-c-.c-o-m~~~~~~~~~~t-e-a-m-2-0-.-c-o-m~~~~~~~~~~~~~~~~~~~~~~
 */
public class AboutFrame extends javax.swing.JFrame {

    /**
     * Creates new form AboutFrame
     */
    public AboutFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pictLBL = new javax.swing.JLabel();
        dlgLBL = new javax.swing.JLabel();
        guessLBL = new javax.swing.JLabel();
        closeBUT = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 255, 153));
        getContentPane().setLayout(null);

        pictLBL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/2011.JPG"))); // NOI18N
        getContentPane().add(pictLBL);
        pictLBL.setBounds(70, 50, 703, 387);

        dlgLBL.setFont(new java.awt.Font("Arial Unicode MS", 1, 24)); // NOI18N
        dlgLBL.setForeground(new java.awt.Color(204, 0, 0));
        dlgLBL.setText("Class of 2011 APCS - Sample by mr Hanley");
        getContentPane().add(dlgLBL);
        dlgLBL.setBounds(140, 10, 520, 30);

        guessLBL.setFont(new java.awt.Font("Arial Unicode MS", 1, 24)); // NOI18N
        guessLBL.setForeground(new java.awt.Color(204, 0, 0));
        guessLBL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        guessLBL.setText("Can you interpret the message???");
        getContentPane().add(guessLBL);
        guessLBL.setBounds(80, 450, 700, 30);

        closeBUT.setBackground(new java.awt.Color(255, 255, 51));
        closeBUT.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        closeBUT.setText("Close");
        closeBUT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeBUTActionPerformed(evt);
            }
        });
        getContentPane().add(closeBUT);
        closeBUT.setBounds(340, 510, 120, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeBUTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeBUTActionPerformed
       this.dispose();
    }//GEN-LAST:event_closeBUTActionPerformed

  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeBUT;
    private javax.swing.JLabel dlgLBL;
    private javax.swing.JLabel guessLBL;
    private javax.swing.JLabel pictLBL;
    // End of variables declaration//GEN-END:variables
}
